# Generated by Django 4.2.4 on 2023-10-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticle',
            name='new_author',
            field=models.CharField(blank=True, max_length=300, validators=[profanity.validators.validate_is_profane], verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        ),
    ]
