# Generated by Django 4.2.4 on 2023-10-29 15:25

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_alter_addarticle_new_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticle',
            name='new_author',
            field=models.CharField(blank=True, max_length=300, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
